In [3]:
import pandas as pd

df = pd.read_csv('Titanic-Dataset.csv')
df.head()  ##read first 5 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.info()  # check columns, types, missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [5]:
df.describe()  # statistics for numerical columns

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [6]:
df.columns #check columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [7]:
df.shape #shape of dataset (row,column)

(891, 12)

In [8]:
df['Sex'].value_counts() #value counts for a column

Sex
male      577
female    314
Name: count, dtype: int64

In [9]:
df.isnull().sum() #check for missing values

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [12]:
ages = df['Age'] ## select single column
subset = df[['Name','Age','Fare']] #select multiple columns
old_passenger = df[df['Age'] > 30] ## Filter rows
adult_males = df[(df['Age'] > 18) & (df['Sex'] == 'male')]

In [13]:
# Fill missing numerical values with mean
df['Age'] = df['Age'].fillna(df['Age'].mean())

# Fill missing categorical with mode
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

# Drop a column you don’t need
df.drop(columns=['Cabin'], inplace=True, errors='ignore')

In [21]:
df['Sex'] = df['Sex'].map({   ##encoding map to numeric
    'male':0,
    'female':1
})

In [ ]:
# One-hot encoding for multiple categories
df = pd.get_dummies(df, columns=['Embarked'])

In [16]:
df['FamilySize'] = df['SibSp'] + df['Parch'] ##create new column

# Transform column (log, square root, etc.)
import numpy as np
df['Fare_log'] = np.log1p(df['Fare'])

In [19]:
df.groupby('Pclass')['Fare'].mean() #Mean fare by class

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [18]:
df.groupby('Sex')['Survived'].sum() #count survivors by gender

Sex
0    109
1    233
Name: Survived, dtype: int64

In [20]:
df.groupby('Pclass').agg({  #multiple aggregation
    'Fare':'mean',
    'Age':'max'
})

             Fare   Age
Pclass
1       84.154687  80.0
2       20.662183  70.0
3       13.675550  74.0

In [22]:
df.sort_values('Fare',ascending = False).head() #sort fare by descending order

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked_C,Embarked_Q,Embarked_S,FamilySize,Fare_log
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",NaN,36.0,0,1,PC 17755,512.3292,True,False,False,1,6.240917
258,259,1,1,"Ward, Miss. Anna",NaN,35.0,0,0,PC 17755,512.3292,True,False,False,0,6.240917
737,738,1,1,"Lesurer, Mr. Gustave J",NaN,35.0,0,0,PC 17755,512.3292,True,False,False,0,6.240917
88,89,1,1,"Fortune, Miss. Mabel Helen",NaN,23.0,3,2,19950,263.0000,False,False,True,5,5.575949
438,439,0,1,"Fortune, Mr. Mark",NaN,64.0,1,4,19950,263.0000,False,False,True,5,5.575949

In [23]:
df.sort_values(['Pclass','Fare'], ascending=[True,False]).head() #sort by multiple columns

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked_C,Embarked_Q,Embarked_S,FamilySize,Fare_log
258,259,1,1,"Ward, Miss. Anna",NaN,35.0,0,0,PC 17755,512.3292,True,False,False,0,6.240917
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",NaN,36.0,0,1,PC 17755,512.3292,True,False,False,1,6.240917
737,738,1,1,"Lesurer, Mr. Gustave J",NaN,35.0,0,0,PC 17755,512.3292,True,False,False,0,6.240917
27,28,0,1,"Fortune, Mr. Charles Alexander",NaN,19.0,3,2,19950,263.0000,False,False,True,5,5.575949
88,89,1,1,"Fortune, Miss. Mabel Helen",NaN,23.0,3,2,19950,263.0000,False,False,True,5,5.575949

In [26]:
df.to_csv('titanic_cleaned.csv', index=False) #saved